### ISSUE TITLE
EADDRINUSE error in logs

### ISSUE THREAD

**Issue by schweppy** [poblouin/homebridge-spotify-speaker#14]
Any ideas what’s going on here? Crashing homebridge so have placed the plug-in in a child bridge for now.
![390AE113-B45F-45CC-9E50-873026DB71C9](https://user-images.githubusercontent.com/17147950/156217320-c699cf1f-6183-43d2-8322-60fa5fde064f.jpeg)

**Comment by schweppy** [comment]
Has now changed to this error - 

![Uploading A5D07750-7C29-4591-ABCA-87A089FCB658.jpeg…]()

**Comment by poblouin** [comment]
Hey @schweppy,

Sorry, for some reason I never had the notification about the new issue. Could you send me your plugin's configuration? Based on the error `this.config.devices is not iterable`, I would guess that you don't have any devices defined in your config. That's an error on my side though, the plugin shouldn't crash because of that, I'll fix it.

As for the `EADDRINUSE` error, I'm not really sure what that is 🤔 Do you still have those?
