### ISSUE TITLE
Volume changes on multiple devices

### ISSUE THREAD

**Issue by jveciana** [poblouin/homebridge-spotify-speaker#23]
I've set up the plug-in to control Spotify playback on an Alexa Echo Dot and it works well, except that when I change the volume, the volume also changes on another Alexa device, an Echo Flex. Any ideas why is this happening?

**Comment by poblouin** [comment]
Hello @jveciana, sorry for the late reply, but since you didn't use the issue template I wasn't tagged and just saw this question.

I took a look at the Spotify API and if you pass a device ID (which my plugin is doing), the volume should be set on that device only.

Just to understand the use case, you have your Echo Dot that is playing a song and you have Echo Flex that is playing the same song on the same user account, then when you change the volume on the Dot, it changes on the Flex also?

**Comment by poblouin** [comment]
Hi again, I will close this since I didn't hear back from you. Do not hesitate to re-open and provide more details so that I can assist you.

Thanks!
